### ISSUE TITLE
Le flux RSS des offres d'emploi de GeoRezo ne fonctionne plus

### ISSUE THREAD

**Issue by Guts** [Guts/elpaso#16]
L'adresse du flux RSS ne fonctionne plus : https://georezo.net/extern.php?fid=10
capture : https://screenshots.firefox.com/2BEW6UngFYZh3ZpH/georezo.net

@yjacolin une idée ?

**Comment by yjacolin** [comment]
yep, je regarderai ca bientôt

**Comment by yjacolin** [comment]
cela doit etre bon maintenant !

**Comment by Guts** [comment]
En cliquant sur le lien du flux, j'ai une erreur d'encodage

**Comment by yjacolin** [comment]
C'est l'interpréteur de ton navigateur ... Regard les sources ! (Ctrl+U de mémoire).

**Comment by Guts** [comment]
Sûr ? parce-que mon script semble me dire la même chose sur la mauvais formatage.
En tout cas, visiblement, georezo est down en ce moment :

![georezo_down](https://user-images.githubusercontent.com/1596222/35213736-edec1db6-ff5e-11e7-9207-2f150bc87b48.PNG)

**Comment by yjacolin** [comment]
Oui GeoRezo est down en ce moment, c'est ce que dit ton message, différent du premier (le serveur n'a pas répondu convenablement au délà d'une certaine durée ...).

**Comment by Guts** [comment]
J'ai bien compris, mais comme j'ai testé au même moment, j'en ai profité pour te le signaler ici.

**Comment by yjacolin** [comment]
tu peux retester maintenant :)

**Comment by Guts** [comment]
Donc l'erreur liée au formatage du RSS est rendue ainsi par [feedparser](https://pypi.python.org/pypi/feedparser) :

![georezo_rss_incompleteread](https://user-images.githubusercontent.com/1596222/35214853-d6f26db4-ff62-11e7-88f0-c460931fcbdf.PNG)

La ligne 22 semble toujours incriminée, que j'ouvre le XML avec FF, IE ou Notepad++.

En investigant, je m'aperçois que le fichier du RSS pèse près de 136 Mo  ! En rechargeant 5 mn plus tard, j'obtiens ensuite un fichier de 160 Mo...

J'ai l'impression que le RSS est un stream de la BDD ! Ça doit surcharger ton serveur non ?

**Comment by Guts** [comment]
Ah là ça remarche :) 👍  !

Par contre, je n'ai que 20 éléments par flux, même en passant le paramètre show=40 :

![georezo_rss_length](https://user-images.githubusercontent.com/1596222/35215589-00169e2a-ff65-11e7-9c8c-2411596898a3.PNG)

Mais on s'approche du dénouement, courage @yjacolin  !

**Comment by yjacolin** [comment]
```
$ curl "https://georezo.net/extern.php?fid=10&show=40" -o rss_job.xml
$ ls -lh rss_job.xml                                                                                                                                                                  
-rw-rw-r-- 1 yjacolin 1128 6,2M janv. 22 11:11 rss_job.xml
```
Tu es sur ? Les flux sont en cache de toute façon.

**Comment by yjacolin** [comment]
ah ok ca c'est déjà plus normal :d

**Comment by Guts** [comment]
^^

**Comment by yjacolin** [comment]
tu vérifies bien car j'ai des choses bizarres, comme si avec Curl le contenu s'accumulé ( pas visible dans firefox ni dans le cache côté serveur).

**Comment by yjacolin** [comment]
:$ dernier problème corrigé !

**Comment by yjacolin** [comment]
vas y c'est en cache de toute façon !

**Comment by yjacolin** [comment]
j'ai mis 200 en cache aussi ;)

**Comment by biratchet** [comment]
Test OK avec le flux ESRI et Outlook.
OK, j'ai tout faux, mais c'est ma configuration à l'ONF ;)
Bravo Yves!!
