### ISSUE TITLE
Rapports hebdomadaires

### ISSUE THREAD

**Issue by Guts** [Guts/elpaso#22]
La #14 étant réalisée, mettre en place un récapitulatif hebdomadaire pour suivre facilement l'évolution de l'analyse et la santé de la base.

**Comment by Guts** [comment]
Première mouture très basique (plain-text) mais suffisante pour constater des problèmes.

Cron documenté dans le [wiki](https://github.com/Guts/elpaso/wiki/D%C3%A9ploiement#cron).

**Comment by Guts** [comment]
@marcisenmann : souhaites-tu être recevoir ces rapports qui permettent d'obtenir directement les liens d'édition dans un mail hebdomadaire comme indiqué dans [le guide]( #23) ? 

Aperçu du  rapport :

![image](https://user-images.githubusercontent.com/1596222/36972610-01aec40c-2070-11e8-9746-0d0dc760fe32.png)

**Comment by marcisenmann** [comment]
Yes !

Marc Isenmann
