### ISSUE TITLE
Le flux RSS ne renvoie aucune offre

### ISSUE THREAD

**Issue by Guts** [Guts/elpaso#33]
Je m'aperçois que le flux RSS semble planté :

- https://georezo.net/extern.php?fid=10 : fonctionne mais ne contient aucune offre
- idem en précisant le nombre d'items à récupérer : https://georezo.net/extern.php?fid=10&show=50

**Comment by biratchet** [comment]
J'ai signalé cela à Yves dans un ticket coté GeoRezo, pour tester notre nouvel outil de tickets/support avec les utilisateurs. Mais la recette est poussive...
L'anomalie existe sur Décryptagéo également.

**Comment by Guts** [comment]
Ok, merci. 

En tout cas, c'est comme si le flux n'avait jamais été généré : `<lastBuildDate>Thu, 01 Jan 1970 01:00:00 +0100</lastBuildDate>`

**Comment by Guts** [comment]
@yjacolin si ça peut t'aider, d'après les logs du serveur de développement, le problème est intervenu quelque part entre 15h et 16h le 25 janvier dernier.

**Comment by Guts** [comment]
Autre erreur obtenue mais qui n'apparaît pas systématiquement :

```
XML Parsing Error: junk after document element
Location: https://georezo.net/extern.php?fid=10&show=50
Line Number 2, Column 1:
<b>Warning</b>:  include(/var/www/html//web/blog/config_geoblogrss.php): failed to open stream: No such file or directory in <b>/var/www/html/web/extern.php</b> on line <b>359</b><br />
^
```

**Comment by Guts** [comment]
Nouvelle erreur constatée à base de trop de connexions à la base...

![image](https://user-images.githubusercontent.com/1596222/75896613-a3a60480-5e37-11ea-8193-3b0bd3ba1c6c.png)

**Comment by biratchet** [comment]
Le succès, mon ami, le succès!
Et probablement le manque de monitoring de la BDD et/ou de supervision de l'hébergement...

**Comment by Guts** [comment]
La clâsse quoi 😎 !

Sinon pour info, j'ai presque fini de remettre le projet sur pieds avec un déploiement continu en développement qui n'attend plus que le retour du RSS : https://elgeopaso-dev.herokuapp.com/.

Faites-moi signe :)

**Comment by marcisenmann** [comment]
Salut Julien,
Merci pour toutes tes actions pour remettre le projet en fonction.
On se tient au jus,
Bien à toi,
Marco

**Comment by biratchet** [comment]
Salut Julien, Yves m'a indiqué samedi que le flux est de nouveau fonctionnel, mais je ne vois rien sur ta plateforme de DEV.

**Comment by yjacolin** [comment]
Aller Julien, tout fonctionne maintenant :)

**Comment by biratchet** [comment]
Yes! Le flux est OK sur la page d'accueil de [DecryptaGeo](https://decryptageo.fr/)

**Comment by Guts** [comment]
En effet, le flux semble bien reparti mais tout ne fonctionne pas correctement (en indiquant une longueur https://georezo.net/extern.php?fid=10&show=50) :

![image](https://user-images.githubusercontent.com/1596222/76201463-943a0900-61f3-11ea-9fc6-8adad1331098.png)

Cela ressemble fortement à un problème d'encodage des caractères :

![image](https://user-images.githubusercontent.com/1596222/76201889-47a2fd80-61f4-11ea-8cfa-b6924d1a12aa.png)

A noter que c'est bien encodé sur le forum. @yjacolin vous ne faites plus d'UTF 8 dans les flux ?

Par ailleurs :

> Salut Julien, Yves m'a indiqué samedi que le flux est de nouveau fonctionnel, mais je ne vois rien sur ta plateforme de DEV.

Oui je n'ai pas activé les tâches récurrentes sur le dév.

**Comment by Guts** [comment]
Je ferme ce ticket au profit d'un nouveau plus ciblé #34. Allez, on va y arriver tous ensemble :)
