### ISSUE TITLE
DNS plateforme dév / prod

### ISSUE THREAD

**Issue by Guts** [Guts/elpaso#5]
Permettre de développer sereinement avant intégration dans plateforme de production et clarifier les URLs :

- [x] pointer http://dev.elgeopaso.fr sur le serveur de dév (online.net)
- [x] pointer http://elgeopaso.fr sur le serveur de prod (georezo.net)

**Comment by yjacolin** [comment]
Je ne peux rien faire là ! Le serveur de prod est d'ailleurs déjà fonctionnel, non ?

**Comment by yjacolin** [comment]
bon elgeopasso.fr ne pointe pas sur georezo.net a priori. C'est une config DNS à faire de votre côté (un CNAME vers geotribu.georezo.net)

**Comment by Guts** [comment]
Je t'ai assigné car tu peux m'apporter de l'aide :)

**Comment by Guts** [comment]
@yjacolin : peux-tu faire en sorte que elgeopaso.georezo.net renvoie sur www.elgeopaso.fr stp ?
